sonar.projectKey=astradualsystem_astratech-apps-frontend_26fce81b-eec0-4071-8bb0-511442738889
sonar.qualitygate.wait=true
sonar.projectName=ASTRATECH APPS FRONTEND
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=.gitlab-ci.yml,.gitlab-ci/**/*,*.gitlab-ci.yml,Dockerfile*,*.dockerfile,.dockerignore,docker-compose*.yml, next.config.mjs
sonar.sourceEncoding=UTF-8